# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- None

schedules:
- cron: "0 10 * * *"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'  # Specify Python version
    addToPath: true
  displayName: 'Set Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt  # Install dependencies from requirements.txt
  displayName: 'Install Dependencies'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'smartmoney_service_connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      export AZURE_CLIENT_ID=$(CLIENTID)
      export AZURE_TENANT_ID=$(TENANTID)
      export AZURE_CLIENT_SECRET=$(CLIENTSECRET)
      python example_download_spy.py
  displayName: 'Get Service Principle and Run Python Script'

#- script: |
#    python example_download_spy.py
#  displayName: 'Run Python Script'
